from page.personalCenter_page import PersonalCenterPage
class PersonalCenterBusiness():
    pc = PersonalCenterPage()
    def PersonalCenter(self):
        self.pc.RedPackage()
        self.pc.RedPackageBack()
        self.pc.Score()
        self.pc.ScoreDetailBack()
        self.pc.Balance()
        self.pc.BalanceBack()
        self.pc.ContentManager()
        self.pc.ContentManagerBack()
        self.pc.History()
        self.pc.HistoryBack()
        self.pc.Information()
        self.pc.InsertPersonInformation()
        self.pc.detelePersonInformation()
        self.pc.InformationBack()
        self.pc.Invoices()
        self.pc.toTime()
        self.pc.InvoicesBack()
        self.pc.InviteFriends()
        self.pc.InviteFriendsBack()
        self.pc.OnlineService()
        self.pc.OnlineServiceBack()
        self.pc.Card()
        self.pc.CardBack()
        self.pc.InviteLandlord()
        self.pc.InviteLandlordBack()
        self.pc.SecurityCenter()
        self.pc.SecurityCenterBack()
        self.pc.Trusteeship()
        self.pc.TrusteeshipBack()
        # self.pc.toWodeSettingHouseDetail()
